# Generated by Django 3.2.3 on 2021-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('TweetId', models.AutoField(primary_key=True, serialize=False)),
                ('TweetUser', models.CharField(max_length=100)),
                ('TweetCreateDate', models.DateField()),
                ('TweetSentiment', models.CharField(max_length=100)),
            ],
        ),
    ]
